# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='sorna',
  # syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x05sorna\"C\n\x0c\x41gentRequest\x12%\n\x08req_type\x18\x01 \x01(\x0e\x32\x13.sorna.AgentReqType\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"\x1d\n\rAgentResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t*;\n\x0c\x41gentReqType\x12\r\n\tHEARTBEAT\x10\x00\x12\x0f\n\x0bSOCKET_INFO\x10\x01\x12\x0b\n\x07\x45XECUTE\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_AGENTREQTYPE = _descriptor.EnumDescriptor(
  name='AgentReqType',
  full_name='sorna.AgentReqType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEARTBEAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOCKET_INFO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=122,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_AGENTREQTYPE)

AgentReqType = enum_type_wrapper.EnumTypeWrapper(_AGENTREQTYPE)
HEARTBEAT = 0
SOCKET_INFO = 1
EXECUTE = 2



_AGENTREQUEST = _descriptor.Descriptor(
  name='AgentRequest',
  full_name='sorna.AgentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_type', full_name='sorna.AgentRequest.req_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='sorna.AgentRequest.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  # syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=89,
)


_AGENTRESPONSE = _descriptor.Descriptor(
  name='AgentResponse',
  full_name='sorna.AgentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='sorna.AgentResponse.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  # syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=120,
)

_AGENTREQUEST.fields_by_name['req_type'].enum_type = _AGENTREQTYPE
DESCRIPTOR.message_types_by_name['AgentRequest'] = _AGENTREQUEST
DESCRIPTOR.message_types_by_name['AgentResponse'] = _AGENTRESPONSE
DESCRIPTOR.enum_types_by_name['AgentReqType'] = _AGENTREQTYPE

AgentRequest = _reflection.GeneratedProtocolMessageType('AgentRequest', (_message.Message,), dict(
  DESCRIPTOR = _AGENTREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:sorna.AgentRequest)
  ))
_sym_db.RegisterMessage(AgentRequest)

AgentResponse = _reflection.GeneratedProtocolMessageType('AgentResponse', (_message.Message,), dict(
  DESCRIPTOR = _AGENTRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:sorna.AgentResponse)
  ))
_sym_db.RegisterMessage(AgentResponse)


# @@protoc_insertion_point(module_scope)
