# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='sorna',
  # syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x05sorna\"T\n\x0eManagerRequest\x12!\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x11.sorna.ActionType\x12\x11\n\tkernel_id\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"S\n\x0fManagerResponse\x12\x1f\n\x05reply\x18\x01 \x01(\x0e\x32\x10.sorna.ReplyType\x12\x11\n\tkernel_id\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t*<\n\nActionType\x12\x08\n\x04PING\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\x0b\n\x07\x44\x45STROY\x10\x02\x12\x0b\n\x07\x45XECUTE\x10\x03*E\n\tReplyType\x12\x08\n\x04PONG\x10\x00\x12\x0c\n\x07SUCCESS\x10\xc8\x01\x12\x12\n\rINVALID_INPUT\x10\x90\x03\x12\x0c\n\x07\x46\x41ILURE\x10\xf4\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='sorna.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DESTROY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=191,
  serialized_end=251,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
_REPLYTYPE = _descriptor.EnumDescriptor(
  name='ReplyType',
  full_name='sorna.ReplyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PONG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_INPUT', index=2, number=400,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=3, number=500,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=253,
  serialized_end=322,
)
_sym_db.RegisterEnumDescriptor(_REPLYTYPE)

ReplyType = enum_type_wrapper.EnumTypeWrapper(_REPLYTYPE)
PING = 0
CREATE = 1
DESTROY = 2
EXECUTE = 3
PONG = 0
SUCCESS = 200
INVALID_INPUT = 400
FAILURE = 500



_MANAGERREQUEST = _descriptor.Descriptor(
  name='ManagerRequest',
  full_name='sorna.ManagerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='sorna.ManagerRequest.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_id', full_name='sorna.ManagerRequest.kernel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='sorna.ManagerRequest.body', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  # syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=104,
)


_MANAGERRESPONSE = _descriptor.Descriptor(
  name='ManagerResponse',
  full_name='sorna.ManagerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='sorna.ManagerResponse.reply', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_id', full_name='sorna.ManagerResponse.kernel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='sorna.ManagerResponse.body', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  # syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=189,
)

_MANAGERREQUEST.fields_by_name['action'].enum_type = _ACTIONTYPE
_MANAGERRESPONSE.fields_by_name['reply'].enum_type = _REPLYTYPE
DESCRIPTOR.message_types_by_name['ManagerRequest'] = _MANAGERREQUEST
DESCRIPTOR.message_types_by_name['ManagerResponse'] = _MANAGERRESPONSE
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE
DESCRIPTOR.enum_types_by_name['ReplyType'] = _REPLYTYPE

ManagerRequest = _reflection.GeneratedProtocolMessageType('ManagerRequest', (_message.Message,), dict(
  DESCRIPTOR = _MANAGERREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:sorna.ManagerRequest)
  ))
_sym_db.RegisterMessage(ManagerRequest)

ManagerResponse = _reflection.GeneratedProtocolMessageType('ManagerResponse', (_message.Message,), dict(
  DESCRIPTOR = _MANAGERRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:sorna.ManagerResponse)
  ))
_sym_db.RegisterMessage(ManagerResponse)


# @@protoc_insertion_point(module_scope)
