# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='sorna',
  # syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x05sorna\"R\n\x0cInputMessage\x12!\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x11.sorna.ActionType\x12\x11\n\tkernel_id\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"T\n\rOutputMessage\x12\x1f\n\x05reply\x18\x01 \x01(\x0e\x32\x10.sorna.ReplyType\x12\x11\n\tkernel_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t*<\n\nActionType\x12\x08\n\x04PING\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\x0b\n\x07\x44\x45STROY\x10\x02\x12\x0b\n\x07\x45XECUTE\x10\x03*&\n\tReplyType\x12\x08\n\x04PONG\x10\x00\x12\x0f\n\x0bKERNEL_INFO\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='sorna.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DESTROY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=190,
  serialized_end=250,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
_REPLYTYPE = _descriptor.EnumDescriptor(
  name='ReplyType',
  full_name='sorna.ReplyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PONG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KERNEL_INFO', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=252,
  serialized_end=290,
)
_sym_db.RegisterEnumDescriptor(_REPLYTYPE)

ReplyType = enum_type_wrapper.EnumTypeWrapper(_REPLYTYPE)
PING = 0
CREATE = 1
DESTROY = 2
EXECUTE = 3
PONG = 0
KERNEL_INFO = 1



_INPUTMESSAGE = _descriptor.Descriptor(
  name='InputMessage',
  full_name='sorna.InputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='sorna.InputMessage.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_id', full_name='sorna.InputMessage.kernel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='sorna.InputMessage.body', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  # syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=102,
)


_OUTPUTMESSAGE = _descriptor.Descriptor(
  name='OutputMessage',
  full_name='sorna.OutputMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='sorna.OutputMessage.reply', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_id', full_name='sorna.OutputMessage.kernel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='sorna.OutputMessage.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  # syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=188,
)

_INPUTMESSAGE.fields_by_name['action'].enum_type = _ACTIONTYPE
_OUTPUTMESSAGE.fields_by_name['reply'].enum_type = _REPLYTYPE
DESCRIPTOR.message_types_by_name['InputMessage'] = _INPUTMESSAGE
DESCRIPTOR.message_types_by_name['OutputMessage'] = _OUTPUTMESSAGE
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE
DESCRIPTOR.enum_types_by_name['ReplyType'] = _REPLYTYPE

InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:sorna.InputMessage)
  ))
_sym_db.RegisterMessage(InputMessage)

OutputMessage = _reflection.GeneratedProtocolMessageType('OutputMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:sorna.OutputMessage)
  ))
_sym_db.RegisterMessage(OutputMessage)


# @@protoc_insertion_point(module_scope)
