ignore:
  - src/ai/backend/manager/models/alembic
coverage:
  status:
    project:
      default:
        threshold: 5%
        paths: src
        informational: true
    patch:
      default:
        threshold: 5%
        paths: src
        informational: true
