- Now all CLI commands are accessible via ``backend.ai mgr``. [(lablup/backend.ai#101)](https://github.com/lablup/backend.ai/issues/101)
- Add more convenient manager CLI commands: `etcd quote`, `etcd unquote`, `etcd move-subtree`
- Add `--short` and `--installed` options to the `etcd list-images` command.
- Add a minimum-occupied slot first scheduler.
