"""add_vfolder_type_column

Revision ID: 529113b08c2c
Revises: f5530eccf202
Create Date: 2020-04-09 16:37:35.460936

"""
import textwrap
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from ai.backend.manager.models import VFolderPermission, VFolderType
from ai.backend.manager.models.base import EnumValueType


# revision identifiers, used by Alembic.
revision = '529113b08c2c'
down_revision = 'f5530eccf202'
branch_labels = None
depends_on = None

vfperm_choices = list(map(lambda v: v.value, VFolderPermission))
# vfolderpermission type should already be defined.
# vfolderpermission = postgresql.ENUM(
#     *vfperm_choices,
#     name='vfolderpermission',
# )

vftype_choices = list(map(lambda v: v.value, VFolderType))
vfoldertype = postgresql.ENUM(
    *vftype_choices,
    name='vfoldertype',
)


def upgrade():
    vfoldertype.create(op.get_bind())
    op.add_column('vfolder_invitations',
                  sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'vfolders',
        sa.Column('type', sa.Enum(*vftype_choices, name='vfoldertype'), nullable=True)
    )
    op.add_column(
        'vfolders',
        sa.Column('permission', sa.Enum(*vfperm_choices, name='vfolderpermission'),
                  nullable=True)
    )

    # Fill vfolders.c.type with 'general' and vfolders.c.permission with 'rw'.
    query = textwrap.dedent('''\
        UPDATE vfolders SET "type" = 'general', permission = 'rw';\
    ''')
    conn = op.get_bind()
    conn.execute(query)

    # Create indexes for name and type.
    op.create_index(op.f('ix_vfolders_name'), 'vfolders', ['name'], unique=False)
    op.create_index(op.f('ix_vfolders_type'), 'vfolders', ['type'], unique=False)

    op.alter_column('vfolders', column_name='type', nullable=False)
    op.alter_column('vfolders', column_name='permission', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vfolders_type'), table_name='vfolders')
    op.drop_index(op.f('ix_vfolders_name'), table_name='vfolders')
    op.drop_column('vfolders', 'type')
    op.drop_column('vfolders', 'permission')
    op.drop_column('vfolder_invitations', 'modified_at')
    vfoldertype.drop(op.get_bind())
    # ### end Alembic commands ###
