"""pipeline-data-models

Revision ID: d27a80a2a4cc
Revises: 60a1effa77d2
Create Date: 2021-12-24 07:14:58.527848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import ai.backend.manager.models.base

# revision identifiers, used by Alembic.
revision = 'd27a80a2a4cc'
down_revision = '60a1effa77d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pipeline_module_tag',
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('name', name=op.f('pk_pipeline_module_tag')),
    )
    op.create_table(
        'pipeline_module',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('icon', sa.String(length=256), nullable=False),
        sa.Column('type', sa.Enum('COMPUTE_SESSION', 'MANAGER_TASK', name='pipeline_module_types'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('domain_name', sa.String(length=64), nullable=False),
        sa.Column('group_id', ai.backend.manager.models.base.GUID(), nullable=False),
        sa.Column('user_uuid', ai.backend.manager.models.base.GUID(), nullable=False),
        sa.Column('active_version', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], name=op.f('fk_pipeline_module_domain_name_domains')),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_pipeline_module_group_id_groups')),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_pipeline_module_user_uuid_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_module')),
    )
    op.create_index(op.f('ix_pipeline_module_created_at'), 'pipeline_module', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_module_modified_at'), 'pipeline_module', ['modified_at'], unique=False)
    op.create_index(op.f('ix_pipeline_module_type'), 'pipeline_module', ['type'], unique=False)
    op.create_table(
        'pipeline_template',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('domain_name', sa.String(length=64), nullable=False),
        sa.Column('group_id', ai.backend.manager.models.base.GUID(), nullable=False),
        sa.Column('user_uuid', ai.backend.manager.models.base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('active_version', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], name=op.f('fk_pipeline_template_domain_name_domains')),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_pipeline_template_group_id_groups')),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_pipeline_template_user_uuid_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_template')),
    )
    op.create_index(op.f('ix_pipeline_template_created_at'), 'pipeline_template', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_template_modified_at'), 'pipeline_template', ['modified_at'], unique=False)
    op.create_table(
        'pipeline_module_input',
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_module.id'], name=op.f('fk_pipeline_module_input_module_id_pipeline_module'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('module_id', 'name', name=op.f('pk_pipeline_module_input')),
    )
    op.create_table(
        'pipeline_module_output',
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_module.id'], name=op.f('fk_pipeline_module_output_module_id_pipeline_module'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('module_id', 'name', name=op.f('pk_pipeline_module_output')),
    )
    op.create_table(
        'pipeline_module_tag_association',
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tag_name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_module.id'], name=op.f('fk_pipeline_module_tag_association_module_id_pipeline_module'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_name'], ['pipeline_module_tag.name'], name=op.f('fk_pipeline_module_tag_association_tag_name_pipeline_module_tag'), onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('module_id', 'tag_name', name=op.f('pk_pipeline_module_tag_association')),
    )
    op.create_table(
        'pipeline_module_version',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('task_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_module.id'], name=op.f('fk_pipeline_module_version_module_id_pipeline_module'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_module_version')),
    )
    op.create_index('idx_pipeline_module_version', 'pipeline_module_version', ['module_id', 'version'], unique=True)
    op.create_index(op.f('ix_pipeline_module_version_created_at'), 'pipeline_module_version', ['created_at'], unique=False)
    op.create_table(
        'pipeline_template_version',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['template_id'], ['pipeline_template.id'], name=op.f('fk_pipeline_template_version_template_id_pipeline_template')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_template_version')),
    )
    op.create_index('idx_pipeline_template_version', 'pipeline_template_version', ['template_id', 'version'], unique=True)
    op.create_table(
        'pipeline',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'FINISHED', 'ERROR', 'CANCELLED', name='pipeline_status'), nullable=False),
        sa.Column('status_info', sa.String(length=64), nullable=True),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('template_vid', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('domain_name', sa.String(length=64), nullable=False),
        sa.Column('group_id', ai.backend.manager.models.base.GUID(), nullable=False),
        sa.Column('user_uuid', ai.backend.manager.models.base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('reserved_start_time', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
        sa.Column('target_termination_time', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
        sa.Column('vfolder', ai.backend.manager.models.base.GUID(), nullable=True),
        sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], name=op.f('fk_pipeline_domain_name_domains')),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_pipeline_group_id_groups')),
        sa.ForeignKeyConstraint(['template_id'], ['pipeline_template.id'], name=op.f('fk_pipeline_template_id_pipeline_template'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['template_vid'], ['pipeline_template_version.id'], name=op.f('fk_pipeline_template_vid_pipeline_template_version'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_pipeline_user_uuid_users')),
        sa.ForeignKeyConstraint(['vfolder'], ['vfolders.id'], name=op.f('fk_pipeline_vfolder_vfolders'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline')),
    )
    op.create_index(op.f('ix_pipeline_created_at'), 'pipeline', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_last_updated'), 'pipeline', ['last_updated'], unique=False)
    op.create_index(op.f('ix_pipeline_reserved_start_time'), 'pipeline', ['reserved_start_time'], unique=False)
    op.create_index(op.f('ix_pipeline_status'), 'pipeline', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_target_termination_time'), 'pipeline', ['target_termination_time'], unique=False)
    op.create_table(
        'pipeline_template_task',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('icon', sa.String(length=256), nullable=False),
        sa.Column('type', sa.Enum('COMPUTE_SESSION', 'MANAGER_TASK', name='pipeline_module_types'), nullable=False),
        sa.Column('task_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('template_vid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('module_vid', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('layout_coord_x', sa.Integer(), nullable=False),
        sa.Column('layout_coord_y', sa.Integer(), nullable=False),
        sa.Column('layout_width', sa.Integer(), nullable=False),
        sa.Column('layout_height', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_module.id'], name=op.f('fk_pipeline_template_task_module_id_pipeline_module'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['module_vid'], ['pipeline_module_version.id'], name=op.f('fk_pipeline_template_task_module_vid_pipeline_module_version'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['template_id'], ['pipeline_template.id'], name=op.f('fk_pipeline_template_task_template_id_pipeline_template'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['template_vid'], ['pipeline_template_version.id'], name=op.f('fk_pipeline_template_task_template_vid_pipeline_template_version'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_template_task')),
    )
    op.create_index(op.f('ix_pipeline_template_task_type'), 'pipeline_template_task', ['type'], unique=False)
    op.create_table(
        'pipeline_template_task_input',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_template_task.id'], name=op.f('fk_pipeline_template_task_input_module_id_pipeline_template_task'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'module_id', 'name', name=op.f('pk_pipeline_template_task_input')),
    )
    op.create_table(
        'pipeline_template_task_output',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_template_task.id'], name=op.f('fk_pipeline_template_task_output_module_id_pipeline_template_task'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'module_id', 'name', name=op.f('pk_pipeline_template_task_output')),
    )
    op.create_table(
        'pipeline_task',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('icon', sa.String(length=256), nullable=False),
        sa.Column('type', sa.Enum('COMPUTE_SESSION', 'MANAGER_TASK', name='pipeline_module_types'), nullable=False),
        sa.Column('task_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'ERROR', 'CANCELLED', name='pipeline_task_status'), nullable=False),
        sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('layout_coord_x', sa.Integer(), nullable=False),
        sa.Column('layout_coord_y', sa.Integer(), nullable=False),
        sa.Column('layout_width', sa.Integer(), nullable=False),
        sa.Column('layout_height', sa.Integer(), nullable=False),
        sa.Column('session_id', ai.backend.manager.models.base.SessionIDColumnType(), nullable=True),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], name=op.f('fk_pipeline_task_pipeline_id_pipeline'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['session_id'], ['kernels.session_id'], name=op.f('fk_pipeline_task_session_id_kernels'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_task')),
    )
    op.create_index(op.f('ix_pipeline_task_last_updated'), 'pipeline_task', ['last_updated'], unique=False)
    op.create_index(op.f('ix_pipeline_task_status'), 'pipeline_task', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_task_type'), 'pipeline_task', ['type'], unique=False)
    op.create_table(
        'pipeline_template_task_link',
        sa.Column('template_vid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_output_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_input_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['task_input_id'], ['pipeline_template_task_input.id'], name=op.f('fk_pipeline_template_task_link_task_input_id_pipeline_template_task_input'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_output_id'], ['pipeline_template_task_output.id'], name=op.f('fk_pipeline_template_task_link_task_output_id_pipeline_template_task_output'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['template_vid'], ['pipeline_template_version.id'], name=op.f('fk_pipeline_template_task_link_template_vid_pipeline_template_version'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('template_vid', 'task_output_id', 'task_input_id', name=op.f('pk_pipeline_template_task_link')),
    )
    op.create_table('pipeline_task_input',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_task.id'], name=op.f('fk_pipeline_task_input_module_id_pipeline_task'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'module_id', 'name', name=op.f('pk_pipeline_task_input')),
    )
    op.create_table(
        'pipeline_task_output',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('module_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['module_id'], ['pipeline_task.id'], name=op.f('fk_pipeline_task_output_module_id_pipeline_task'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'module_id', 'name', name=op.f('pk_pipeline_task_output')),
    )
    op.create_table(
        'pipeline_task_link',
        sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_output_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_input_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], name=op.f('fk_pipeline_task_link_pipeline_id_pipeline'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_input_id'], ['pipeline_task_input.id'], name=op.f('fk_pipeline_task_link_task_input_id_pipeline_task_input'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_output_id'], ['pipeline_task_output.id'], name=op.f('fk_pipeline_task_link_task_output_id_pipeline_task_output'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('pipeline_id', 'task_output_id', 'task_input_id', name=op.f('pk_pipeline_task_link')),
    )
    op.add_column('kernels', sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), server_default=sa.text('NULL'), nullable=True))
    op.create_foreign_key(op.f('fk_kernels_pipeline_id_pipeline'), 'kernels', 'pipeline', ['pipeline_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_kernels_pipeline_id_pipeline'), 'kernels', type_='foreignkey')
    op.drop_column('kernels', 'pipeline_id')
    op.drop_table('pipeline_task_link')
    op.drop_table('pipeline_task_output')
    op.drop_table('pipeline_task_input')
    op.drop_table('pipeline_template_task_link')
    op.drop_index(op.f('ix_pipeline_task_type'), table_name='pipeline_task')
    op.drop_index(op.f('ix_pipeline_task_status'), table_name='pipeline_task')
    op.drop_index(op.f('ix_pipeline_task_last_updated'), table_name='pipeline_task')
    op.drop_table('pipeline_task')
    op.drop_table('pipeline_template_task_output')
    op.drop_table('pipeline_template_task_input')
    op.drop_index(op.f('ix_pipeline_template_task_type'), table_name='pipeline_template_task')
    op.drop_table('pipeline_template_task')
    op.drop_index(op.f('ix_pipeline_target_termination_time'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_status'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_reserved_start_time'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_last_updated'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_created_at'), table_name='pipeline')
    op.drop_table('pipeline')
    op.drop_index('idx_pipeline_template_version', table_name='pipeline_template_version')
    op.drop_table('pipeline_template_version')
    op.drop_index(op.f('ix_pipeline_module_version_created_at'), table_name='pipeline_module_version')
    op.drop_index('idx_pipeline_module_version', table_name='pipeline_module_version')
    op.drop_table('pipeline_module_version')
    op.drop_table('pipeline_module_tag_association')
    op.drop_table('pipeline_module_output')
    op.drop_table('pipeline_module_input')
    op.drop_index(op.f('ix_pipeline_template_modified_at'), table_name='pipeline_template')
    op.drop_index(op.f('ix_pipeline_template_created_at'), table_name='pipeline_template')
    op.drop_table('pipeline_template')
    op.drop_index(op.f('ix_pipeline_module_type'), table_name='pipeline_module')
    op.drop_index(op.f('ix_pipeline_module_modified_at'), table_name='pipeline_module')
    op.drop_index(op.f('ix_pipeline_module_created_at'), table_name='pipeline_module')
    op.drop_table('pipeline_module')
    op.drop_table('pipeline_module_tag')
    # ### end Alembic commands ###
