"""add user model

Revision ID: be5a257f01b2
Revises: 8e660aa31fe3
Create Date: 2019-04-30 23:16:46.644808

"""
from alembic import op
import sqlalchemy as sa
import ai.backend.manager.models.base  # noqa


# revision identifiers, used by Alembic.
revision = 'be5a257f01b2'
down_revision = '8e660aa31fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
