"""multicontainer-sessions

Revision ID: e56d214b6c99
Revises: 10e39a34eed5
Create Date: 2018-11-19 01:17:47.293072

"""
from alembic import op
import sqlalchemy as sa
import ai.backend.manager.models.base  # noqa


# revision identifiers, used by Alembic.
revision = 'e56d214b6c99'
down_revision = '10e39a34eed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kernels', sa.Column('bundle_id', sa.String(length=64), nullable=True))
    op.add_column('kernels', sa.Column('network_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_kernels_bundle_id'), 'kernels', ['bundle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kernels_bundle_id'), table_name='kernels')
    op.drop_column('kernels', 'network_id')
    op.drop_column('kernels', 'bundle_id')
    # ### end Alembic commands ###
